SELECT HISTORY_ID, CAR_ID, to_char(START_DATE, 'yyyy-mm-dd') AS START_DATE, to_char(END_DATE, 'yyyy-mm-dd') AS END_DATE,
    CASE WHEN (END_DATE - START_DATE + 1) >= 30 THEN '장기 대여'
    ELSE '단기 대여'
    END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_CHAR(START_DATE, 'YYYY-MM') = '2022-09'
ORDER BY HISTORY_ID DESC